backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: HeroImage, name: heroImage, widget: image }
          - {
              label: "hero background Image",
              name: backgroundHero,
              widget: image,
            }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - { label: "Main Pitch", name: mainpitch, widget: string }
          - {
              label: "Main Pitch Description",
              name: mainpitchdesc,
              widget: string,
            }
          - { label: "main pitch image", name: mainpitchImage, widget: image }
          - { label: "Option Img 2", name: optionImg2, widget: image }
          - { label: "Option Img 3", name: optionImg3, widget: image }
          - { label: "Option Img 4", name: optionImg4, widget: image }
          - { label: "Option Img 5", name: optionImg5, widget: image }
          - {
              label: "Collection Img 1-1",
              name: collectionImg_1_1,
              widget: image,
            }
          - {
              label: "Collection Img 1-2",
              name: collectionImg_1_2,
              widget: image,
            }
          - {
              label: "Collection Img 2-1",
              name: collectionImg_2_1,
              widget: image,
            }
          - {
              label: "Collection Img 2-2",
              name: collectionImg_2_2,
              widget: image,
            }
          - { label: "Show Case Img 1", name: showCase1, widget: image }
          - { label: "Show Case Img 2", name: showCase2, widget: image }
          - { label: "Show Case Img 3", name: showCase3, widget: image }
          - { label: "Social Img 1", name: socialImg1, widget: image }
          - { label: "Social Img 2", name: socialImg2, widget: image }
          - { label: "Social Img 3", name: socialImg3, widget: image }
          - { label: "Social Img 4", name: socialImg4, widget: image }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: "About Image", name: aboutImage, widget: image }
      - file: "src/pages/shop/index.md"
        label: "Shop"
        name: "shop"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "shop-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subheading", name: "subheading", widget: "string" }
          - { label: "Carousel Pic 1", name: carouselPic1, widget: image }
          - { label: "Carousel Pic 2", name: carouselPic2, widget: image }
          - { label: "Carousel Pic 3", name: carouselPic3, widget: image }
          - { label: "Carousel Pic 4", name: carouselPic4, widget: image }
          - { label: "Carousel Pic 5", name: carouselPic5, widget: image }
          - { label: "Product Desc Img 3", name: productDesc3, widget: image }
          - { label: "Product Desc Img 4", name: productDesc4, widget: image }
          - { label: "Select img 1", name: selectCore1, widget: image }
          - { label: "Social Img 1", name: socialImg1, widget: image }
          - { label: "Social Img 2", name: socialImg2, widget: image }
          - { label: "Social Img 3", name: socialImg3, widget: image }
          - { label: "Social Img 4", name: socialImg4, widget: image }
      - file: "src/pages/contact/index.md"
        label: "Contact"
        name: "contact"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "contact-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Contact Text", name: "contactText", widget: "string" }
          - { label: "Contact Image", name: contactImg, widget: image }
      - file: "src/pages/wholesale/index.md"
        label: "Wholesale"
        name: "wholesale"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "wholesale-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subheading", name: "subheading", widget: "string" }
          - { label: "Contact Title", name: bulkContactTitle, widget: string }
          - { label: "Wholesale Text", name: "wholesaleText", widget: "string" }
          - { label: "Business Text", name: "businessText", widget: "string" }
          - { label: "Bulk Image", name: bulkImg, widget: image }
      - file: "src/pages/shipping-policy/index.md"
        label: "Shipping Policy"
        name: "shipping-policy"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "shipping-policy",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" } 
  - name: "blog"
            label: "Blog"
            folder: "src/pages/blog"
            create: true
            slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
            fields:
              - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
              - {label: "Featured Image", name: "featuredimage", widget: image}
              - {label: "Body", name: "body", widget: "markdown"}
